<?php

/**
 * @category    Digiselfie
 * @package     Digiselfie_Login
 * @author      Digiselfie Inc.
 */

?>
<div class="digiselfielogin-login">
    <div class="account-login">
        <div class="<?php echo $this->_getColSet(); ?> digiselfielogin-login-lower">
            <?php if($this->_digiselfieEnabled()): ?>
            <div class="<?php echo $this->_getButtCol(); ?> digiselfielogin-login-lower">
                <?php echo $this->getChildHtml('digiselfie_login_button'); ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
