<?php

/**
 * @category    Digiselfie
 * @package     Digiselfie_Login
 * @author      Digiselfie Inc.
 */
?>

<div class="digiselfielogin-register">
    <div class="<?php echo $this->_getColSet(); ?> fieldset">
        <?php if($this->_digiselfieEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> digiselfielogin-register">
          <?php echo $this->getChildHtml('digiselfie_login_checkout_button')?>
        </div>
        <?php endif; ?>
    </div>
</div>
